version: '3'

services:
  php:
    build:
      context: ./dev/docker/config
      dockerfile: dockerfile
    volumes:
      - ./dev/docker/config/php.ini:/usr/local/etc/php/php.ini
      - ./dev/docker/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./dev/docker/config/.bashrc:/root/.bashrc
      - ./system-dist/html:/var/www/html
      - ./system-dist/log:/var/log
    ports:
      - 8005:80
    tty: true
    stdin_open: true
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./dev/docker/mysql:/var/lib/mysql
    ports:
      - 13305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./dev/docker/config/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
      - ./dev/docker/phpmyadmin/sessions:/sessions
    ports:
      - 4005:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test
    links:
      - mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"