FROM php:8.0-apache
RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
  vim \
  libonig-dev \
  sendmail \
  libzip-dev
RUN apt-get install -y --no-install-recommends poppler-utils
RUN docker-php-ext-install \
  pdo_mysql \
  mysqli \
  zip \
  mbstring
RUN curl -sSLO https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
    && chmod +x mhsendmail_linux_amd64 \
    && mv mhsendmail_linux_amd64 /usr/local/bin/mhsendmail \
    && echo 'sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/conf.d/sendmail.ini
RUN a2enmod rewrite
