FROM php:7.4-apache
RUN set -xe \
  && apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    vim libonig-dev
RUN docker-php-ext-install \
    pdo_mysql \
    mysqli \
    mbstring
RUN pecl install xdebug \
  && docker-php-ext-enable xdebug
RUN a2enmod rewrite